server:
  port: 10086
spring:
  profiles:
    active: dev
  application:
    name: signup-app
  datasource:
    url: jdbc:mysql://121.37.10.43:3306/signup?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: myx_+123456
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  redis:
    database: 5
    # Redis服务器地址
    host: 139.9.206.60
    # Redis服务器连接端口
    port: 6379
    password: Rr123456

mybatis:
  mapper-locations: classpath:/mapping/*.xml
  configuration:
    map-underscore-to-camel-case: true

file-system:
  upload-path: /signup/files
  outer-prefix: https://ac-sfs.obs.cn-south-1.myhuaweicloud.com

logging:
  file:
    path: /root/signup/logs
  level:
    root: info
